# Generated by Django 5.2.4 on 2025-08-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='extraction_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='extraction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='extraction_results',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
